- name: Install some packages
  hosts: all
  tasks:
    - name: Install a superior text editor
      ansible.builtin.package:
        name: vim

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when:
        - ansible_pkg_mgr is "dnf"

    - name: Upgrade all packages
      ansible.builtin.yum:
        name: "*"
        state: latest
      when:
        - ansible_pkg_mgr is "yum"

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: yes
      when:
        - ansible_pkg_mgr is "apt"
